server:
  port: ${SERVER-PORT:8081}
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: demo-1
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA-SERVER:localhost}:${SERVER-PORT:8084}/eureka/
